config/routes.rb
Rails.application.routes.draw do
  #Study Routes
  get '/', to: 'studies#root', as: 'root'
  get 'studies', to: 'studies#index', as: 'studies_index'
  get 'studies/new', to: 'studies#new', as: 'new_study'
  post 'studies/create', to: 'studies#create', as: 'create_study'
  get 'studies/edit/:id', to: 'studies#edit', as: 'edit_study'
  patch 'studies/update/:id', to: 'studies#update', as: 'update_study'
  get 'studies/destroy/:id', to: 'studies#destroy', as: 'delete_study'
  get 'studies/report/:id', to: 'studies#report', as: 'generate_report'

  #Site Routes
  get 'sites', to: 'sites#index', as: 'sites_index'
  get 'sites/study_id', to: 'sites#show', as: 'show_site'
  get 'sites/new', to: 'sites#new', as: 'new_site'
  #get 'studies/:study_id/sites/new', to: 'sites#new', as: 'new_site'
  post 'sites/create', to: 'sites#create', as: 'create_site'
  get 'sites/edit/:id', to: 'sites#edit', as: 'edit_site'
  patch 'sites/update/:id', to: 'sites#update', as: 'update_site'
  get 'sites/destroy/:id', to: 'sites#destroy', as: 'delete_site'

  #Subject Routes
  get 'subjects/index', to: 'subjects#index', as: 'subjects_index'
  get 'subjects/site_id', to: 'subjects#show', as: 'show_subjects'
  get 'subjects/new', to: 'subjects#new', as: 'new_subject'
  post 'subjects/create', to: 'subjects#create', as: 'create_subject'
  get 'subjects/feedback/:id', to: 'subjects#feedback', as: 'subject_feedback'
  patch 'subjects/rate/:id', to: 'subjects#rate', as: 'rate_by_subject'
  get 'subjects/update_sites', as: 'update_sites'
  get 'subjects/edit/:id', to: 'subjects#edit', as: 'edit_sub'
  patch 'subjects/update/:id', to: 'subjects#update', as: 'update_sub'
  get 'subjects/destroy/:id', to: 'subjects#destroy', as: 'delete_sub'

  #Trial Progress
  get 'progress', to: 'trial_progress#progress', as: 'progress'
  get 'progress/study_id', to: 'trial_progress#show_progress', as: 'show_progress'
  get 'status/study_id', to: 'trial_progress#show_status', as: 'show_status'
  patch 'progress/study_id', to: 'trial_progress#mark_complete', as: 'mark_complete'
end

app/models/study.rb
class Study < ApplicationRecord
  has_many :sites, dependent: :destroy
  has_many :subjects, through: :sites

  #Model Level Validations
  validates :title, uniqueness: true
  validates :title, :therapeutic_area, :no_of_subjects, presence: true
  validates :title, length: {in: 6..20}
  validates :phase, numericality: {less_than_or_equal_to: 5}
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  def root
  end

  def index
    @studies = Study.all
  end

  def new
    Rails.logger.info "Inside New"
    @study = Study.new
  end

  def create
    #save study received via form into database
    @study = Study.new(study_params)
    if @study.save
      redirect_to studies_index_path
    else
      render :new
    end
  end

  def edit
    @study = Study.find(params[:id])
  end

  def update
    @study = Study.find(params[:id])
    if @study.update(study_params)
      redirect_to studies_index_path
    else
      render :edit
    end
  end

  def destroy
    @study = Study.find(params[:id])
    # #destroy subjects associated to each site
    # @study.sites.each do |site|
    #   site.subjects.destroy
    # end
    #
    # #destroy sites associated to study
    # @study.sites.destroy
    #destroy study
    if @study.destroy
      redirect_to studies_index_path
    else
      render plain: 'cant be deleted'
    end
  end

  def study_params
    params.require(:study).permit(:title, :therapeutic_area, :phase, :status, :start_date)
  end

end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_study_row.html.erb
<tr>
  <td> <%= study.title %> </td>
  <td> <%= study.therapeutic_area %> </td>
  <td> <%= study.phase %> </td>
  <td> <%= study.start_date %> </td>
  <td> <%= study.projected_end_date %> </td>
  <td> <%= study.no_of_subjects %> </td>
  <% if study.redacted.eql? true %>
    <td> <%= link_to image_tag("red.png", size: "20x20") %></td>
  <% else %>
    <td> <%= link_to image_tag("green.png", size: "20x20") %></td>
  <% end %>
  <td> <%= link_to image_tag("edit.png", :size => "20x20"), edit_study_path(study.id) %> </td>
  <td> <%= link_to image_tag("delete.png", :size => "20x20"), delete_study_path(study.id), data: { confirm: 'All the associated sites and subjects will be deleted. Confirm delete?' } %> </td>
  <td> <%= link_to image_tag("report.png", :size => "30x30"), generate_report_path(study.id) %> </td>
</tr>

app/views/studies/edit.html.erb
<div class="title-container">
  <h3> Edit Study</h3>
</div>

<% if @study.errors.full_messages.present? %>
  <% @study.errors.full_messages.each do |error_message| %>
    <ul>
      <li style="color: #c62531"><%= error_message %></li>
    </ul>
  <% end %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_with(model: @study, url: update_study_path, html: { class: "form-horizontal"}) do |f| %>

      <div class="form-group">
        <%= f.label "Title", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :title %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Therapeutic Area", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :therapeutic_area %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Phase", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.number_field :phase %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Status", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.select :status, ['Planned', 'Preparation', 'Open', 'Execution', 'Completed', 'Closed', 'Hold', 'Stopped', 'Cancelled'], value: @study.status %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Start Date", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.date_field :start_date, as: :date , value: @study.start_date.to_s.try(:strftime, '%m/%d/%Y')%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Projected End Date".upcase_first, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.date_field :projected_end_date, as: :date, value: @study.projected_end_date.to_s.try(:strftime, '%m/%d/%Y')%>
        </div>
      </div>
<!--      value: date_convert(@study.projected_end_date.to_s)-->

      <div class="form-group">
        <%= f.label "No Of Subjects", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.number_field :no_of_subjects %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-11 col-sm-offset-1">
          <%= f.submit "UPDATE" %>
        </div>
      </div>

      <h5><%=link_to 'Go Back', studies_index_path%></h5>

    <% end %>
  </div>
</div>

app/views/studies/index.html.erb
<div id="header" style="clear:both">
  <h2 style="float: left">Study Management</h2>
  <h2 style=" float: right; margin-left: 15px"> <%= link_to '+Add', new_study_path, class: "new-study" %></h2>
</div>

<div id="table_body">
  <div id=table>
    <table>
      <tr>
        <th> Title</th>
        <th> Therapeutic Area</th>
        <th> Phase</th>
        <th> Start End</th>
        <th> Projected End Date</th>
        <th> No Of Subjects</th>
        <th> Redacted </th>
        <th> Edit </th>
        <th> Delete </th>
        <th> Generate Report </th>
      </tr>
      <% @studies.each do |study| %>
        <%= render partial: 'study_row', locals: { study: study } %>
      <% end %>
    </table>
  </div>
  <h5><%=link_to 'Go Back', root_path%></h5>
  <% flash.each do |type, msg|%>
    <div style="color: green; margin-left: 300px">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/studies/new.html.erb
<div class="title-container">
  <h3> Create Study </h3>
</div>

<% if @study.errors.full_messages.present? %>
  <% @study.errors.full_messages.each do |message| %>
    <ul>
      <li style="color: #c62531"><%= message %></li>
    </ul>
  <% end %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_with(model: @study, url: create_study_path, html: { class: "form-horizontal" }) do |f| %>

      <div class="form-group">
        <%= f.label "Title", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :title %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Therapeutic Area", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :therapeutic_area %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Phase", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.number_field :phase %>
        </div>
      </div>

<!--      <div class="form-group">-->
        <%#= f.label "Status", class: "col-sm-1 control-label" %>
<!--        <div class="col-sm-11">-->
          <%#= f.select :status, ['Planned', 'Preparation', 'Open', 'Execution', 'Completed', 'Closed', 'Hold', 'Stopped', 'Cancelled'] %>
          <%#= f.select :status, ['Not Started', 'In Progress', 'Completed'] %>
<!--        </div>-->
<!--      </div>-->

      <div class="form-group">
        <%= f.label "Start Date", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.date_field :start_date, as: :date %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Projected End Date".upcase_first, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.date_field :projected_end_date, as: :date %>
        </div>
      </div>
      <%#= f.text_field :projected_end_date, type: "date"%>
      <div class="form-group">
        <%= f.label "No Of Subjects", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.number_field :no_of_subjects %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-11 col-sm-offset-1">
          <%= f.submit "SAVE" %>
        </div>
      </div>

      <h5><%= link_to 'Go Back', studies_index_path %></h5>

    <% end %>
  </div>
</div>


<!--html: { :style => 'background-color:red; ' })-->

app/views/studies/root.html.erb
<h2 style="margin-left: 10px; color-interpolation-filters: linearRGB">WELCOME TO MINI MEDIDATA</h2>
<hr/>
<div class="root-div" , style="margin-left: 20px">
  <h3><%= link_to 'Study Management', studies_index_path %> </h3>
  <h3><%= link_to 'Site Management', sites_index_path %> </h3>
  <h3><%= link_to 'Subject Management', subjects_index_path %> </h3>
  <hr/>
<!--  <h3><%#= link_to 'Trial Progress', progress_path %></h3>-->
</div>