config/routes.rb
Rails.application.routes.draw do
  #Study Routes
  get '/', to: 'studies#root', as: 'root'
  get 'studies', to: 'studies#index', as: 'studies_index'
  get 'studies/new', to: 'studies#new', as: 'new_study'
  post 'studies/create', to: 'studies#create', as: 'create_study'
  get 'studies/edit/:id', to: 'studies#edit', as: 'edit_study'
  patch 'studies/update/:id', to: 'studies#update', as: 'update_study'
  get 'studies/destroy/:id', to: 'studies#destroy', as: 'delete_study'
  get 'studies/report/:id', to: 'studies#report', as: 'generate_report'

  #Site Routes
  get 'sites', to: 'sites#index', as: 'sites_index'
  get 'sites/study_id', to: 'sites#show', as: 'show_site'
  get 'sites/new', to: 'sites#new', as: 'new_site'
  #get 'studies/:study_id/sites/new', to: 'sites#new', as: 'new_site'
  post 'sites/create', to: 'sites#create', as: 'create_site'
  get 'sites/edit/:id', to: 'sites#edit', as: 'edit_site'
  patch 'sites/update/:id', to: 'sites#update', as: 'update_site'
  get 'sites/destroy/:id', to: 'sites#destroy', as: 'delete_site'

  #Subject Routes
  get 'subjects/index', to: 'subjects#index', as: 'subjects_index'
  get 'subjects/site_id', to: 'subjects#show', as: 'show_subjects'
  get 'subjects/new', to: 'subjects#new', as: 'new_subject'
  post 'subjects/create', to: 'subjects#create', as: 'create_subject'
  get 'subjects/feedback/:id', to: 'subjects#feedback', as: 'subject_feedback'
  patch 'subjects/rate/:id', to: 'subjects#rate', as: 'rate_by_subject'
  get 'subjects/update_sites', as: 'update_sites'
  get 'subjects/edit/:id', to: 'subjects#edit', as: 'edit_sub'
  patch 'subjects/update/:id', to: 'subjects#update', as: 'update_sub'
  get 'subjects/destroy/:id', to: 'subjects#destroy', as: 'delete_sub'

  #Trial Progress
  get 'progress', to: 'trial_progress#progress', as: 'progress'
  get 'progress/study_id', to: 'trial_progress#show_progress', as: 'show_progress'
  get 'status/study_id', to: 'trial_progress#show_status', as: 'show_status'
  patch 'progress/study_id', to: 'trial_progress#mark_complete', as: 'mark_complete'
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :site

  validates :name, :screening_no, presence: true
  # validate :end_date_later_than_enrolled_date
  #
  # def end_date_later_than_enrolled_date
  #   error_msg = 'End date cannot be earlier than enrolled date'
  #   if end_date <= enrollment_date
  #   errors.add(:end_date, error_msg)
  #   end
  # end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @site_id = ''
    get_study_site_for_select
    @subjects = ''
  end

  def show
    get_study_site_for_select
    @site_id = params[:site_id]
    @subjects = Subject.where(site_id: params[:site_id])
    render :index
  end

  def create
    #ForbiddenAttributesError.html
    # @subject = Subject.new(params[:subject])
    @subject = Subject.new(subject_params)
    # if @subject.invalid?
    #   render :new
    # else
    # if Subject.where(site_id: subject_params[:site_id]).size < Site.find(subject_params[:site_id]).no_of_subjects.to_i
    #    @subject.save
    #    redirect_to subjects_index_path, notice: "Subject have been added to Site: #{Site.find(params[:subject][:site_id]).name}..."
    # else
    #     redirect_to subjects_index_path, notice: "Subject cannot be added, maximum limit is reached"
    # end
    # end
    if @subject.invalid?
      render :new

    else

      #total no of subjects specified in study
      current_study = Study.find(Site.find(subject_params[:site_id]).study_id)
      study_sub_count = current_study.no_of_subjects
      Rails.logger.info "Study Sub Count>>>> #{study_sub_count}"

      #total no of subjects allocated to all the sites belonging to this study
      site_sub_count = 0
      current_site = Site.find(subject_params[:site_id])
      current_study.sites.each { |site| site_sub_count += site.no_of_subjects }
      Rails.logger.info "Site Sub Count>>>> #{site_sub_count}"

      if site_sub_count < study_sub_count
        @subject.save
        #Send the mail to subject
        SubjectMailer.with(subject: @subject).welcome_mail.deliver_later
        current_site.update(no_of_subjects: current_site.no_of_subjects + 1)
        redirect_to subjects_index_path, notice: "Subject have been added to Site: #{Site.find(params[:subject][:site_id]).name}..."
      else
        redirect_to subjects_index_path, notice: "Subject cannot be added, maximum limit of subjects for study is reached"
      end

    end
  end

  def new
    @subject = Subject.new
  end

  def feedback
    @subject = Subject.find(params[:id])
  end

  def rate
    @subject = Subject.find_by("id = ?", params[:id])
    rating = params[:subject][:rating]
    if @subject.update(rating: rating)
      redirect_to subjects_index_path, notice: "Rating is captured!"
    end
    #render json: {sub: @subject}
    # if @subject.update(rating: params[] )
    # render plain: 'OK'
    # {"param_key":{"_method":"patch","authenticity_token":"zeumNJbZoeu2rGQX364s84nOEQqQF-jx43E5lK6J9IFsTq2O9u74ihZyzdIX_4f
    # VwMNrXb07UlNa30kfQFvr5A","subject":{"rating":"Neutral"},"commit":"SUBMIT","controller":"subjects","action":"rate","id":"10"}}
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to subjects_index_path
    else
      render :edit
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    if @subject.destroy
      @parent_site = Site.find(@subject.site_id)
      @parent_site.update(no_of_subjects: @parent_site.no_of_subjects - 1)
      redirect_to subjects_index_path
    else
      render plain: "cant be deleted"
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :screening_no, :status, :enrollment_date, :end_date, :site_id, :email)
  end

  def get_study_site_for_select

    @studies = Study.all
    #@sites = Site.find_by("study_id = ?")
  end

  def update_sites
    @sites = Site.where("study_id = ?", params[:study_id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_subject_row.html.erb
<tr>
  <td> <%= subject.name %> </td>
  <td> <%= subject.screening_no %> </td>
  <td> <%= subject.status %> </td>
  <td> <%= subject.enrollment_date %> </td>
  <td> <%= subject.end_date %> </td>
  <td> <%= subject.email %> </td>
  <% if rating.eql? false %>
    <td> <%= link_to image_tag('rating.png', size: "30x30"), subject_feedback_path(subject.id), :style => 'background-color:red;' %> </td>
  <% else %>
    <td style="color:green;"> Rating Captured!</td>
  <% end %>
  <% if subject.active.eql? true %>
    <td> <%= link_to image_tag('check.png', size: "20x20") %> </td>
  <% else %>
    <td> <%= link_to image_tag('cross.png', size: "20x20") %></td>
  <% end %>
  <td> <%= link_to image_tag("edit.png", :size => "20x20"), edit_sub_path(subject.id) %> </td>
  <td> <%= link_to image_tag("delete.png", :size => "20x20"), delete_sub_path(subject.id), data: { confirm: 'Subject will be deleted. Confirm delete?' } %> </td>
</tr>

app/views/subjects/create.html.erb
<h1>Subjects#create</h1>
<p>Find me in app/views/subjects/create.html.erb</p>

app/views/subjects/edit.html.erb
<div class="title-container">
  <h3> Edit Subject</h3>
</div>

<% if @subject.errors.full_messages.present? %>
  <ul>
    <% @subject.errors.full_messages.each do |error_msg| %>
      <li style="color: #B00100"> <%= error_msg %> </li>
    <% end %>
  </ul>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_with(model: @subject, url: update_sub_path, html: { class: "form-horizontal" }) do |f| %>

      <div class="form-group">
        <%= f.label "Name", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Screening No", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.number_field :screening_no %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Status", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.select :status, ['Screening', 'Screening Failed', 'Enrolled', 'Early Termination', 'Completed'] %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Enrollment Date", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.date_field :enrollment_date, as: :date, value: @subject.enrollment_date.to_s.try(:strftime, '%m/%d/%Y') %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "End Date", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.date_field :end_date, as: :date, value: @subject.end_date.to_s.try(:strftime, '%m/%d/%Y') %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Email", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.email_field :email %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-11 col-sm-offset-1">
          <%= f.submit "UPDATE" %>
        </div>
      </div>

      <h5><%= link_to 'Go Back', subjects_index_path %></h5>

    <% end %>
  </div>
</div>

app/views/subjects/feedback.html.erb
<!--<div class="header-1">-->
<!--  <div class="rating-header">-->
<!--  <h2>Feedback Form</h2>-->
<!--  </div>-->
<!--</div>-->
<div class="title-container" style="margin-left: 20px">
  <h2>Feedback Form</h2>
</div>

<div class="rating-div">
  <div class="panel-body">
  <pre> Hello <b><i><%= @subject.name %></b></i>

        Please provide your feedback for the drug <b><i><%= Study.find(Site.find(@subject.site_id).study_id).title %> </i></b>
        You have undergone trial at <b><i><%= Site.find(@subject.site_id).name %></b></i>
        <%= form_with(model: @subject, url: rate_by_subject_path) do |f|%>
          <p>
            <b>Rating</b>
           <%= f.radio_button :rating, 'Happy' %> Happy
           <%= f.radio_button :rating, 'Neutral' %> Neutral
           <%= f.radio_button :rating, 'Sad' %> Sad
            <%#= radio_button_tag :rating, '1' %><%#= label_tag :purpose_feedback, 'Happy' %>
            <%#= radio_button_tag :rating, '2' %><%#= label_tag :purpose_prayer, 'Neutral' %>
            <%#= radio_button_tag :rating, '3' %><%#= label_tag :purpose_praise, 'Sad' %>
            <%= f.submit 'SUBMIT' %>
          </p>
        <% end %>
        Thank you!
 </pre>
  </div>
  <h5><%= link_to 'Go Back', subjects_index_path %></h5>
</div>

app/views/subjects/index.html.erb
<div class="header-1">
  <div id="site-header" style="clear:both">
    <h2 style="float: left">Subject Management</h2>
    <h2 style=" float: right; margin-left: 15px"> <%= link_to '+Add', new_subject_path, class: "new-study" %></h2>
  </div>
</div>>

<!--<div class="study-search">-->
<%#= form_with(url: show_subjects_path(:site_id), method: :get, html: { style: 'font-size:16px' }) do |f| %>
<%#= f.label 'Select Study' %>
<%#= f.select :id, Study.all.collect { |study| [study.title, study.id] }, { :include_blank => "--Choose--" } %>
<%#= f.label 'Select Site' %>
<%#= f.select :site_id, Site.all.collect { |site| [site.name, site.id] }, { :include_blank => "--Choose--" } %>
<!--    <div class="btn btn-sm" , style="display: inline">-->
<%#= f.submit "GO" %>
<!--    </div>-->
<%# end %>
<!--</div>-->

<div class="study-search">
  <%= form_with(url: show_subjects_path(:site_id), method: :get, html: { style: 'font-size:16px' }) do |f| %>
    <%= f.label 'Select Site' %>
    <%= f.select :site_id, Site.all.collect { |site| [site.name, site.id] }, { :include_blank => "--Choose--" } %>
    <div class="btn btn-sm" , style="display: inline">
      <%= f.submit "GO" %>
    </div>
  <% end %>
</div>

<div style="margin-left: 10px; color: #666666; clear: both; position: absolute">
  <div style="float: left">
  <%= label_tag 'Study:' %>
  <%= @site_id.empty? ? '' : Study.find(Site.find(@site_id).study_id).title%>
  </div>

  <div style="float: right;margin-left: 15px">
    <%= label_tag 'Expected No Of Subjects:' %>
    <%= @site_id.empty? ? '': Study.find(Site.find(@site_id).study_id).no_of_subjects%>
  </div>

  <div style="float: left; margin-left: 15px">
    <%= label_tag 'Site:'%>
    <%= @site_id.empty? ? '' : Site.find(@site_id).name%>
  </div>
</div>

<div id="site_table_body">
  <div id=table>
    <table>
      <tr>
        <th> Name</th>
        <th> Screening No</th>
        <th> Status</th>
        <th> Enrolled Date</th>
        <th> End Date</th>
        <th> Email</th>
        <th> Rate Drug</th>
        <th> Active </th>
        <th> Edit</th>
        <th> Delete</th>
      </tr>
      <% if @subjects.empty? %>
        <tr>
          <td colspan="10" style="text-align: center;"> No Subjects Found</td>
        </tr>
      <% else %>
        <% @subjects.each do |subject| %>
          <% if subject.rating.nil? %>
            <%= render partial: 'subject_row', locals: { subject: subject, rating: false } %>
          <% else %>
            <%= render partial: 'subject_row', locals: { subject: subject, rating: true } %>
          <% end %>
        <% end %>
      <% end %>
    </table>
  </div>
  <h5><%= link_to 'Go Back', root_path %></h5>

  <% flash.each do |type, msg| %>
    <div style="color: green; font-family: 'Comic Sans MS'; margin-left: 300px">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/subjects/new.html.erb
<div class="title-container">
  <h3> Create Subject </h3>
</div>

<% if @subject.errors.full_messages.present? %>
  <% @subject.errors.full_messages.each do |message| %>
    <ul>
      <li style="color: #c62531"><%= message %></li>
    </ul>
  <% end %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_with(model: @subject, url: create_subject_path, html: { class: "form-horizontal"}) do |f| %>

      <div class="form-group">
        <%= f.label "Name", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Screening No", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.number_field :screening_no %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Status", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.select :status, ['Screening', 'Screening Failed', 'Enrolled', 'Early Termination', 'Completed'] %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Enrollment Date", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :enrollment_date, type: "date"  %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "End Date", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :end_date, type: "date" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Select Site", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.select :site_id, Site.all.collect {|site| [site.name, site.id]}, {:include_blank => "--Choose--"}%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Email", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.email_field :email %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-11 col-sm-offset-1">
          <%= f.submit "SAVE" %>
        </div>
      </div>

      <h5><%=link_to 'Go Back', sites_index_path%></h5>

    <% end %>
  </div>
</div>

<!--html: { :style => 'background-color:red; ' })-->