config/routes.rb
Rails.application.routes.draw do
  #Study Routes
  get '/', to: 'studies#root', as: 'root'
  get 'studies', to: 'studies#index', as: 'studies_index'
  get 'studies/new', to: 'studies#new', as: 'new_study'
  post 'studies/create', to: 'studies#create', as: 'create_study'
  get 'studies/edit/:id', to: 'studies#edit', as: 'edit_study'
  patch 'studies/update/:id', to: 'studies#update', as: 'update_study'
  get 'studies/destroy/:id', to: 'studies#destroy', as: 'delete_study'
  get 'studies/report/:id', to: 'studies#report', as: 'generate_report'

  #Site Routes
  get 'sites', to: 'sites#index', as: 'sites_index'
  get 'sites/study_id', to: 'sites#show', as: 'show_site'
  get 'sites/new', to: 'sites#new', as: 'new_site'
  #get 'studies/:study_id/sites/new', to: 'sites#new', as: 'new_site'
  post 'sites/create', to: 'sites#create', as: 'create_site'
  get 'sites/edit/:id', to: 'sites#edit', as: 'edit_site'
  patch 'sites/update/:id', to: 'sites#update', as: 'update_site'
  get 'sites/destroy/:id', to: 'sites#destroy', as: 'delete_site'

  #Subject Routes
  get 'subjects/index', to: 'subjects#index', as: 'subjects_index'
  get 'subjects/site_id', to: 'subjects#show', as: 'show_subjects'
  get 'subjects/new', to: 'subjects#new', as: 'new_subject'
  post 'subjects/create', to: 'subjects#create', as: 'create_subject'
  get 'subjects/feedback/:id', to: 'subjects#feedback', as: 'subject_feedback'
  patch 'subjects/rate/:id', to: 'subjects#rate', as: 'rate_by_subject'
  get 'subjects/update_sites', as: 'update_sites'
  get 'subjects/edit/:id', to: 'subjects#edit', as: 'edit_sub'
  patch 'subjects/update/:id', to: 'subjects#update', as: 'update_sub'
  get 'subjects/destroy/:id', to: 'subjects#destroy', as: 'delete_sub'

  #Trial Progress
  get 'progress', to: 'trial_progress#progress', as: 'progress'
  get 'progress/study_id', to: 'trial_progress#show_progress', as: 'show_progress'
  get 'status/study_id', to: 'trial_progress#show_status', as: 'show_status'
  patch 'progress/study_id', to: 'trial_progress#mark_complete', as: 'mark_complete'
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :study
  has_many :subjects, dependent: :destroy

  validates :name, presence: true
  validates :no_of_subjects, numericality: true
  #validate :end_date_greater_than_start_date

  # def end_date_greater_than_start_date
  #   binding.pry
  #   error_msg = "site closing date cannot be earlier than site open date"
  #   errors.add(:site_close_date, error_msg) if :site_close_date < :site_open_date
  # end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @study_id = ''
    @sites = ''
  end

  def show
    # @cities = City.where("country_id = ?", Country.first.id)
    @study_id = params[:study_id]
    @sites = Site.where(study_id: params[:study_id])
    render :index
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to sites_index_path, notice: "Site added to Study: #{Study.find(params[:site][:study_id]).title}..."
    else
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      redirect_to sites_index_path, notice: "Site #{@site.name} has been updated..."
    else
      render :edit
    end
  end

  def destroy
    @site = Site.find(params[:id])
    if @site.destroy
      redirect_to sites_index_path
    else
      render plain: 'cant de deleted'
    end
  end

  private

  def site_params
    params.require(:site).permit(:name, :no_of_subjects, :site_open_date, :site_close_date, :screen_failure_rate,
                                 :address, :study_id)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_site.html.erb
<option value="<%= site.id %>"><%= site.name.titleize %></option>

app/views/sites/_site_row.html.erb
<tr>
  <td> <%= site.name %> </td>
  <td> <%= site.no_of_subjects %> </td>
  <td> <%= site.site_open_date %> </td>
  <td> <%= site.site_close_date %> </td>
  <td> <%= site.screen_failure_rate %> </td>
  <td> <%= site.address %> </td>
  <td> <%= link_to image_tag("edit.png", :size => "20x20"), edit_site_path(site.id) %> </td>
  <td> <%= link_to image_tag("delete.png", :size => "20x20"), delete_site_path(site.id), data: {confirm: 'All subjects will be deleted. Confirm delete?'} %> </td>
</tr>

app/views/sites/edit.html.erb
<div class="title-container">
  <h3> Edit Site</h3>
</div>

<% if @site.errors.full_messages.present? %>
  <ul>
    <% @site.errors.full_messages.each do |error_msg| %>
      <li style="color: #B00100"> <%= error_msg %> </li>
    <% end %>
  </ul>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_with(model: @site, url: update_site_path, html: { class: "form-horizontal"}) do |f| %>

      <div class="form-group">
        <%= f.label :name, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :site_open_date, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.date_field :site_open_date, as: :date , value: @site.site_open_date.to_s.try(:strftime, '%m/%d/%Y')%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :site_close_date, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.date_field :site_close_date, as: :date, value: @site.site_close_date.to_s.try(:strftime, '%m/%d/%Y')%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :screen_failure_rate, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.number_field :screen_failure_rate %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :address, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :address %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-11 col-sm-offset-1">
          <%= f.submit "UPDATE" %>
        </div>
      </div>

      <h5><%=link_to 'Go Back', sites_index_path%></h5>

    <% end %>
  </div>
</div>

app/views/sites/index.html.erb
<div class="header-1">
  <div id="site-header" style="clear:both">
    <h2 style="float: left">Site Management</h2>
    <h2 style=" float: right; margin-left: 15px"> <%= link_to '+Add', new_site_path, class: "new-study" %></h2>
  </div>
</div>>

<div class="study-search">
  <%= form_with(url: show_site_path(:study_id), method: :get, html: { style: 'font-size:16px', class: 'form-inline' }) do |f| %>
    <%= f.label 'Select Study' %>
    <%= f.select :study_id, Study.all.collect { |study| [study.title, study.id] }, { :include_blank => "--Choose--" } %>
    <div class="btn btn-sm" , style="display: inline">
      <%= f.submit "GO" %>
    </div>
    <%#= f.submit 'ADD', form_action: new_site_path(study_id: :id) %>
  <% end %>
</div>
<div style="margin-left: 10px;color: #666666">
  <%= label_tag 'Study:' %>
  <%= @study_id.empty? ? '' : Study.find(@study_id).title %>
</div>
<div id="site_table_body">
  <div id=table>
    <table>
      <tr>
        <th> Name</th>
        <th> No Of Subjects</th>
        <th> Site Open Date</th>
        <th> Site Close Date</th>
        <th> Screen Failure Rate</th>
        <th> Address</th>
        <th> Edit</th>
        <th> Delete</th>
      </tr>
      <% if @sites.empty? %>
        <tr>
          <td colspan="8" style="text-align: center;"> No Sites Found</td>
        </tr>
      <% else %>
        <% @sites.each do |site| %>
          <%= render partial: 'site_row', locals: { site: site } %>
        <% end %>
      <% end %>
    </table>
  </div>
  <h5><%= link_to 'Go Back', root_path %></h5>
  <% flash.each do |type, msg| %>
    <div style="color: green; font-family: 'Comic Sans MS'; margin-left: 300px">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/sites/new.html.erb
<div class="title-container">
  <h3> Create Site</h3>
</div>

<% if @site.errors.full_messages.present? %>
  <% @site.errors.full_messages.each do |message| %>
    <ul>
      <li style="color: #c62531"><%= message %></li>
    </ul>
  <% end %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_with(model: @site, url: create_site_path, html: { class: "form-horizontal"}) do |f| %>

      <div class="form-group">
        <%= f.label :name, class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :name %>
        </div>
      </div>

<!--      <div class="form-group">-->
        <%#= f.label "No Of Subjects", class: "col-sm-1 control-label" %>
<!--        <div class="col-sm-11">-->
          <%#= f.number_field :no_of_subjects %>
<!--        </div>-->
<!--      </div>-->

      <div class="form-group">
        <%= f.label "Site Open Date", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :site_open_date, type: "date"  %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Site Close Date", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :site_close_date, type: "date" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Screen Failure Rate", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.number_field :screen_failure_rate %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Address", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.text_field :address %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Select Study", class: "col-sm-1 control-label" %>
        <div class="col-sm-11">
          <%= f.select :study_id, Study.all.collect {|study| [study.title, study.id]}, {:include_blank => "--Choose--"}%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-11 col-sm-offset-1">
          <%= f.submit "SAVE" %>
        </div>
      </div>

      <h5><%=link_to 'Go Back', sites_index_path%></h5>

    <% end %>
  </div>
</div>

<!--html: { :style => 'background-color:red; ' })-->