config/routes.rb
Rails.application.routes.draw do
  #Study Routes
  get '/', to: 'studies#root', as: 'root'
  get 'studies', to: 'studies#index', as: 'studies_index'
  get 'studies/new', to: 'studies#new', as: 'new_study'
  post 'studies/create', to: 'studies#create', as: 'create_study'
  get 'studies/edit/:id', to: 'studies#edit', as: 'edit_study'
  patch 'studies/update/:id', to: 'studies#update', as: 'update_study'
  get 'studies/destroy/:id', to: 'studies#destroy', as: 'delete_study'
  get 'studies/report/:id', to: 'studies#report', as: 'generate_report'

  #Site Routes
  get 'sites', to: 'sites#index', as: 'sites_index'
  get 'sites/study_id', to: 'sites#show', as: 'show_site'
  get 'sites/new', to: 'sites#new', as: 'new_site'
  #get 'studies/:study_id/sites/new', to: 'sites#new', as: 'new_site'
  post 'sites/create', to: 'sites#create', as: 'create_site'
  get 'sites/edit/:id', to: 'sites#edit', as: 'edit_site'
  patch 'sites/update/:id', to: 'sites#update', as: 'update_site'
  get 'sites/destroy/:id', to: 'sites#destroy', as: 'delete_site'

  #Subject Routes
  get 'subjects/index', to: 'subjects#index', as: 'subjects_index'
  get 'subjects/site_id', to: 'subjects#show', as: 'show_subjects'
  get 'subjects/new', to: 'subjects#new', as: 'new_subject'
  post 'subjects/create', to: 'subjects#create', as: 'create_subject'
  get 'subjects/feedback/:id', to: 'subjects#feedback', as: 'subject_feedback'
  patch 'subjects/rate/:id', to: 'subjects#rate', as: 'rate_by_subject'
  get 'subjects/update_sites', as: 'update_sites'
  get 'subjects/edit/:id', to: 'subjects#edit', as: 'edit_sub'
  patch 'subjects/update/:id', to: 'subjects#update', as: 'update_sub'
  get 'subjects/destroy/:id', to: 'subjects#destroy', as: 'delete_sub'

  #Trial Progress
  get 'progress', to: 'trial_progress#progress', as: 'progress'
  get 'progress/study_id', to: 'trial_progress#show_progress', as: 'show_progress'
  get 'status/study_id', to: 'trial_progress#show_status', as: 'show_status'
  patch 'progress/study_id', to: 'trial_progress#mark_complete', as: 'mark_complete'
end

app/controllers/trial_progress_controller.rb
class TrialProgressController < ApplicationController
  def progress
    @study = Study.new
    @happy_percentage = 0
  end

  def show_progress
    @study = Study.find(params[:study_id])
    @subject_count_at_sites = 0
    @study.sites.each { |site| @subject_count_at_sites += site.no_of_subjects }
    @status = ''
    if @subject_count_at_sites < @study.no_of_subjects
      @status = 'Not Started'
    elsif Subject.all.pluck(:rating).include? nil
      @status = 'In Progress'
    else
      @status = 'Completed'
    end
    @happy_percentage = ((@study.subjects.pluck(:rating).count('Happy').to_f) / @study.no_of_subjects.to_f) * 100
    render :progress
  end

  def mark_complete
    Study.find(params[:format]).subjects.all.update(active: false)
    flash.notice = "#{Study.find(params[:format]).subjects.all.size} Subjects is deactivated"
  end

  def show_status
  end
end

app/views/trial_progress/progress.html.erb
<div class="title-container" style="margin-left: 10px">
  <h3>Trial Progress</h3>
</div>

<div class="panel panel-default" style="margin-left: 10px">
  <%= form_with(url: show_progress_path(:study_id), method: :get) do |f| %>
    <%= f.label 'Select Study' %>
    <%= f.select :study_id, Study.all.collect { |study| [study.title, study.id] }, { :include_blank => "--Choose--" } %>
    <%= f.submit 'GO' %>
  <% end %>
  </br>

  <div style="margin-left: 10px">
    <%= label_tag 'site_count', 'No Of Sites:' %>
    <%= text_field_tag 'site_count', @study.sites.size %>
    </br>
    <%= label_tag 'subject_count', 'No Of Subjects Required:' %>
    <%= text_field_tag 'subject_count', @study.no_of_subjects %>
    </br>
    <%= label_tag 'sub_count', 'No Of Subjects Added To Sites:' %>
    <%= text_field_tag 'sub_count', @subject_count_at_sites %>
    </br>
    <%= label_tag 'trial_status', 'Trial Status:' %>
    <%= text_field_tag 'sub_count', @status %>
    </br>

    <% if @status == 'Completed' %>
      <p> Happy Percentage: <%= @happy_percentage %> %</p>
      <% if @happy_percentage > 70 %>
        <%= form_with url: mark_complete_path(@study.id), method: :patch do |form| %>
          <%= form.label :p1, "Study phase will be incremented & Trialled subjects will be deactivated on Mark Complete" %>
          </br>
          <%= form.submit "Mark Complete" %>
        <% end %>
      <% end %>
    <% elsif @status == 'Not Started' %>
      <p> Happy Percentage: NA </p>
    <% end %>

    <% flash.each do |type, msg| %>
      <div style="color: green; font-family: 'Comic Sans MS'; margin-left: 300px">
        <%= msg %>
      </div>
    <% end %>

    <%#= link_to 'Mark the trial as complete', show_status_path %>

  </div>
</div>

app/views/trial_progress/show_progress.html.erb
<h1> HELLO </h1>